config/routes.rb
EzPetSitting::Application.routes.draw do
  get "pages/index"

  get "pages/services"
  get "pages/about"
  get "pages/blog"
  get "pages/reviews"
  get "pages/contact"

  root :to => "users#index"
  resources :users

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def services
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html >
<!--  Website template by freewebsitetemplates.com  -->
<html>

<head>
  <title>EzPetSitting</title>
  <meta  charset=iso-8859-1" />
  <link href="css/style.css" rel="stylesheet" type="text/css" />
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <!--[if IE 6]>
    <link href="css/ie6.css" rel="stylesheet" type="text/css" />
  <![endif]-->
  <!--[if IE 7]>
        <link href="css/ie7.css" rel="stylesheet" type="text/css" />  
  <![endif]-->
</head>

<body>

    
      <div id="header">
                <a href="index.html" id="logo"><%= image_tag("logo.gif", :width=>"310", :height=>"114", :alt=>"", :title=>"") %></a>
          <ul class="navigation">
            <li class="<%= params[:action] == 'index' ? 'active' : ''%>"><a href="/">Home</a></li>
            <li class="<%= params[:action] == 'services' ? 'active' : ''%>"><%= link_to 'Services', pages_services_path%></li>
            <li class="<%= params[:action] == 'about' ? 'active' : ''%>"><%= link_to 'About', pages_about_path%></li>
            <li class="<%= params[:action] == 'blog' ? 'active' : ''%>"><%= link_to 'Blog', pages_blog_path%></li>
            <li class="<%= params[:action] == 'reviews' ? 'active' : ''%>"><%= link_to 'Reviews', pages_reviews_path%></li>
            <li class="<%= params[:action] == 'contact' ? 'active' : ''%>"><%= link_to 'Contact Me', pages_contact_path%></li>
          </ul>
      </div>
      
      <div id="body">
      
          <div class="banner">&nbsp;</div>
          
             <div id="content">
           
               <div class="content">
                 <%= yield %>
            </div>
            
              <div id="sidebar">
                <div class="search">
                  <input type="text" name="s" value="Find"><button>&nbsp;</button>
                  <label for="articles"><input type="radio" id="articles">Here</label>
                  <label for="products"><input type="radio" id="products" checked>Google</label>
                </div>
                
                                <div class="section">                 
                  <ul class="navigation">
                    <li class="active"><a href="index.html">Available Services</a></li>
                    <li><a href="index.html">Specials</a></li>
                  </ul>
                  
                  <div class="aside">
                   <div>
                    <div>
                       <ul>
                        <li><a href="index.html">Express Care</a> <a class="more" href="index.html">see all</a></li>
                        <li><a href="index.html">Hour Care Session</a> <a class="more" href="index.html">see all</a></li>
                        <li><a href="index.html">Extended Walk</a> <a class="more" href="index.html">see all</a></li>
                        <li><a href="index.html">Large Animal</a> <a class="more" href="index.html">see all</a></li>
                        <li><a href="index.html">Washing</a> <a class="more" href="index.html">see all</a></li>
                        <li><a href="index.html">Overnight Care</a> <a class="more" href="index.html">see all</a></li>
                       </ul>
                    </div>
                   </div>
                  </div>
                </div>
                
              </div>
           </div>
           
           <div class="featured">
           </div>
          
      
      </div>
      
      <div id="footer">
              <div class="section">
            <ul>
              <li>
              <%= image_tag "friendly-pets.jpg", :width=>"240", :height=>"186", :alt=>"Pet Shop", :title=>"Pet Shop"%>
                <h2><a href="index.html">Benefits</a></h2>
                <p>
                   Using a professional pet sitter reaps benefits for both pets and pet parents...<a class="more" href="http://www.petsitters.org/benefits_of_using_a_pet_sitter.php">Read More</a> 
                </p>
              </li> 
              <li>
              <%= image_tag "igy.png", :width=>"240", :height=>"186", :alt=>"Pet Shop", :title=>"Pet Shop"%>
                <h2><a href="index.html">Iguanas</a></h2>
                <p>
                Iguanas are one of the most popular reptiles purchased from pet shops today...
                   <a class="more" href="http://www.drexotic.com/care-and-feeding-of-iguanas/">Read More</a> 
                </p>
              </li> 
              <li>
              <%= image_tag "healthy-dog.jpg", :width=>"240", :height=>"186", :alt=>"Pet Shop", :title=>"Pet Shop"%>
                <h2><a href="index.html">Keep them healthy</a></h2>
                <p>
                   Keeping dogs happy, healthy and safe. Nutrition & Feeding · Feeding your dog the right way. AKC Pet Healthcare Plan...<a class="more" href="http://www.akc.org/dogowner/keep_dog_healthy/index.cfm">Read More</a> 
                </p>
              </li> 
              <li>
                
                <h2><a href="index.html">Caring for horses</a></h2>
                <p>
                     Horses kept in pastures should have access to a water tank, ideally in the shade...<a class="more" href="http://www.peta.org/living/companion-animals/caring-for-horses.aspx">Read More</a> 
                </p>
              <%= image_tag "horse.png", :width=>"240", :height=>"186", :alt=>"Pet Shop", :title=>"Pet Shop"%>
              </li> 
            </ul>
          </div>
          <div id="footnote">
            <div class="section">
              <a href="/">EzPetSitting</a>. All Rights Reserved.
            </div>
          </div>
      </div>
      
  
</body>
</html>

app/views/pages/about.html.haml
%h4
  My love for animals began when I was about 9 years old when I started working at a 20- acre horse farm in exchange for riding lessons.
%h4
  I was responsible for feeding and barn maintanance for 20 horses 2 times a day.  
%h4 
  Becoming a pet owner I began caring for all types of pets from horses to dogs and cats to 6 ft iguanas.
%h4
  I became a pet sitter after realizing how difficult it was to find a reliable, caring sitter when your beloved pets could not travel. I believe the best trip results from not worrying about
  your animals while away and you animals being comfortable and cared for while you are gone.
%h4
  I charge reasonable rates with satisfaction guaranteed.  I want you and your animals to be happy and smiling. 
%h4
  Caring for your pets will include greeting them, taking them out to the bathroom/walks/cleaning their litter or bedding, 
  feeding them according to your instructions with fresh water, distribute any medications, followed by a fun play time as well as a final bathroom break before I depart.
%h4
  Each visit typically takes from 45 minutes to 1 hour unless instructed otherwise (additional time will be extra).
%h4
  Additional pet taxi will counts as 1 day visit ($20).
%h4
  I will also bring in mail, newspapers, water indoor and outdoor plants, etc. to keep your house in lived in condition. For any other questions about rates and services, feel free to contact me. 

app/views/pages/blog.html.haml
Blog coming soon....

app/views/pages/contact.html.haml
Contact information coming soon...

app/views/pages/index.html.haml
%h1 Pages#index
%p Find me in app/views/pages/index.html.haml

app/views/pages/reviews.html.haml
Reviews coming soon...

app/views/pages/services.html.haml
%h3 Services
%h5 Day Rates
%ul.paw
  %li $20 / day
  %li $30/ Twice a day
  %li $40/ 3 times a day
  %li Additional $10 Every visit (per day)
  %li $50 Over-night stays
  %li Dog horse
  %li Pet taxi counts as 1 visit ($20 to and from) in the Ocala area only. 
  %li For abnormal requests, please contact me for more information.

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :password
    = f.text_field :password
  .actions
    = f.submit 'Save'

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
%ul
  %li
    .left
      =image_tag 'puppy.jpg'
    .right.marginTop20
      Reliable, caring pettings for the central florida ocala region    
  %li
    .left
      =image_tag 'cat.jpg'
    .right.marginTop20
      Let your pets relax in the comfort of their own home    
  %li
    .left
      =image_tag 'koi.jpg'
    .right.marginTop20
      Have a worry free trip away from your animals    
  %li
    .left
      =image_tag 'bird.jpg'
    .right.marginTop20
      Caring for dogs, cats, horses, snakes, iguanas etc

app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', users_path

app/views/users/show.html.haml
%p#notice= notice

%p
  %b Email:
  = @user.email
%p
  %b Password:
  = @user.password

= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path